# Generated by Django 4.2.30 on 2026-06-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="image",
        ),
        migrations.AddField(
            model_name="complaint",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
